spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC

nrich:
  encrypt:
    encryption-configuration-list:
      - method-to-encrypt-decrypt: net.croz.nrichdemobackend.encrypt.controller.EncryptDemoController.encryptResultDefinedInProperties
        encryption-operation: ENCRYPT
      - method-to-encrypt-decrypt: net.croz.nrichdemobackend.encrypt.controller.EncryptDemoController.decryptArgumentInProperties
        encryption-operation: DECRYPT

  form-configuration:
    form-configuration-mapping:
      form-configuration.demo-request: net.croz.nrichdemobackend.formconfiguration.request.FormConfigurationDemoRequest

logging.level:
  org.hibernate.SQL: debug
